# Generated by Django 3.2.25 on 2026-03-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtag_owner_id', models.CharField(max_length=50)),
                ('rtag_title', models.CharField(max_length=150)),
            ],
        ),
    ]
