# Generated by Django 3.2.25 on 2026-03-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtag',
            name='rtag_elevation',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtag',
            name='rtag_latitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtag',
            name='rtag_longitude',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20, max_length=40),
            preserve_default=False,
        ),
    ]
