# Generated by Django 3.2.25 on 2026-03-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtags', '0002_auto_20260311_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rtag',
        ),
    ]
