# Generated by Django 3.2.25 on 2026-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_title', models.CharField(max_length=60)),
                ('challenge_description', models.TextField()),
                ('challenge_created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
