# Generated by Django 3.2.25 on 2026-03-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
