# Generated by Django 3.2.25 on 2026-03-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scoreboard',
        ),
    ]
