# Generated by Django 3.2.25 on 2026-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('challenge_id', models.CharField(max_length=25)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=20, max_length=40)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=20, max_length=40)),
                ('elevation', models.DecimalField(decimal_places=20, max_digits=20, max_length=40)),
            ],
        ),
    ]
