# Generated by Django 3.2.25 on 2026-03-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rtag',
        ),
    ]
